# Generated by Django 4.0.2 on 2022-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220310_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmodel',
            name='slogan',
            field=models.CharField(default='', max_length=30, verbose_name='标语'),
        ),
    ]
