# Generated by Django 4.0.2 on 2022-03-12 07:51

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_labelmodel_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='邮箱')),
                ('content', mdeditor.fields.MDTextField(verbose_name='评论内容')),
                ('blog', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='博客')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
