# Generated by Django 4.0.2 on 2022-03-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_labelmodel_slogan'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecommentmodel',
            options={'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterField(
            model_name='articlecommentmodel',
            name='blog',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='博客ID'),
        ),
        migrations.AlterModelTable(
            name='articlecommentmodel',
            table='blog_comments',
        ),
    ]
