# Generated by Django 3.2 on 2022-03-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_articlecommentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecommentmodel',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='parent comment id'),
        ),
    ]
