# Generated by Django 3.2 on 2022-03-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_articlecommentmodel_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecommentmodel',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='反对数'),
        ),
        migrations.AddField(
            model_name='articlecommentmodel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='赞同数'),
        ),
        migrations.AddField(
            model_name='articlecommentmodel',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='articlecommentmodel',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='父评论ID'),
        ),
    ]
